# Generated by Django 5.0.6 on 2024-05-22 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('HOS_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('HOS_NAME', models.TextField()),
                ('HOS_ADDRESS', models.TextField()),
                ('HOS_CONTACT', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PAT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PAT_NAME', models.TextField()),
                ('PAT_BIRTH', models.TextField()),
                ('PAT_ADDRESS', models.TextField(blank=True, null=True)),
                ('PAT_CONTACT', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DOC_ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('DOC_PW', models.TextField()),
                ('DOC_NAME', models.TextField()),
                ('DOC_CONTACT', models.TextField()),
                ('DOC_MAJOR', models.TextField()),
                ('HOS_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='XImage',
            fields=[
                ('XIMAGE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('POSITION', models.TextField(blank=True, null=True)),
                ('XIMAGE_GENDER', models.TextField(blank=True, null=True)),
                ('XIMAGE_AGE', models.IntegerField(blank=True, null=True)),
                ('XIMAGE_PATH', models.ImageField(blank=True, null=True, upload_to='ximages/')),
                ('PAT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.patient')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='DOC_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.doctor'),
        ),
        migrations.CreateModel(
            name='MIR',
            fields=[
                ('XIMAGE_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalog.ximage')),
                ('MIR_RESULT', models.FloatField()),
                ('MIR_MIR', models.TextField()),
                ('MIR_DATE', models.DateTimeField(auto_now_add=True)),
                ('DOC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.doctor')),
            ],
        ),
    ]
